apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: asset_value_points
spec:
  database:
    postgres:
      uri:
        value: will-be-overridden
  name: asset_value_points
  schema:
    postgres:
      primaryKey:
        - id
      columns:
        - name: id
          type: uuid
          default: "gen_random_uuid()"
          constraints:
            notNull: true
        - name: asset_id
          type: varchar(50)
          constraints:
            notNull: true
        - name: user_id
          type: uuid
          constraints:
            notNull: true
        - name: timestamp
          type: timestamp
          default: "now()"
          constraints:
            notNull: true
        - name: value
          type: numeric(15,2)
          constraints:
            notNull: true
        - name: currency
          type: varchar(3)
          constraints:
            notNull: true
