apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: users
spec:
  name: users
  schema:
    postgres:
      primaryKey:
        - id
      columns:
        - name: id
          type: uuid
          default: "gen_random_uuid()"
          constraints:
            notNull: true
        - name: username
          type: varchar(255)
          constraints:
            notNull: true
        - name: password_hash
          type: varchar(255)
          constraints:
            notNull: true
        - name: created_at
          type: timestamp
          default: "now()"
          constraints:
            notNull: true
      indexes:
        - columns:
            - username
          isUnique: true
          name: idx_users_username_unique
