apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asset-tracker.fullname" . }}-backend
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.jwtSecret }}
