apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asset-tracker.fullname" . }}-frontend
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "asset-tracker.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- include "asset-tracker.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: frontend
          image: {{ include "asset-tracker.proxyImage" (dict "root" . "image" (printf "docker.io/%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag)) }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
