{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "asset-tracker.fullname" . }}
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
  {{- if and (index .Values "cert-manager" "enabled") .Values.certManager.email }}
  annotations:
    cert-manager.io/cluster-issuer: {{ include "asset-tracker.fullname" . }}-letsencrypt
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and (index .Values "cert-manager" "enabled") .Values.certManager.email .Values.ingress.host }}
  tls:
    - secretName: {{ include "asset-tracker.fullname" . }}-tls
      hosts:
        - {{ .Values.ingress.host }}
  {{- else if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "asset-tracker.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "asset-tracker.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
