apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asset-tracker.fullname" . }}-postgres
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  user: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}
  database: {{ .Values.postgres.database }}
