apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asset-tracker.fullname" . }}-pgdata
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
