apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asset-tracker.fullname" . }}-schema
  labels:
    {{- include "asset-tracker.labels" . | nindent 4 }}
data:
  schema.sql: |
    {{- .Files.Get "schema.sql" | nindent 4 }}
