apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: asset-tracker
spec:
  chart:
    name: asset-tracker
    chartVersion: 0.1.0
  releaseName: asset-tracker
  weight: 20
  values:
    global:
      localRegistry:
        host: '{{repl HasLocalRegistry | ternary LocalRegistryHost "" }}'
        namespace: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace "" }}'
    ingress:
      enabled: true
      className: nginx
    ingress-nginx:
      enabled: true
      controller:
        image:
          registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.k8s.io" }}'
          image: '{{repl HasLocalRegistry | ternary (printf "%s/controller" LocalRegistryNamespace) "ingress-nginx/controller" }}'
        service:
          type: '{{repl if eq Distribution "embedded-cluster" }}NodePort{{repl else }}LoadBalancer{{repl end }}'
          nodePorts:
            http: '{{repl if eq Distribution "embedded-cluster" }}30080{{repl else }}{{repl end }}'
        admissionWebhooks:
          patch:
            image:
              registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.k8s.io" }}'
              image: '{{repl HasLocalRegistry | ternary (printf "%s/kube-webhook-certgen" LocalRegistryNamespace) "ingress-nginx/kube-webhook-certgen" }}'
    postgresql:
      image:
        repository: '{{repl HasLocalRegistry | ternary (printf "%s/%s/postgres" LocalRegistryHost LocalRegistryNamespace) "docker.io/library/postgres" }}'
    replicated:
      image:
        registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "proxy.replicated.com" }}'
        repository: '{{repl HasLocalRegistry | ternary (printf "%s/replicated-sdk-image" LocalRegistryNamespace) "library/replicated-sdk-image" }}'
    backend:
      analyticsEnabled: '{{repl LicenseFieldValue "analytics_enabled" }}'
    mailpit:
      enabled: true
  optionalValues:
    - when: '{{repl ConfigOptionEquals "postgres_type" "embedded" }}'
      recursiveMerge: true
      values:
        postgresql:
          enabled: true
          auth:
            password: '{{repl ConfigOption "postgres_embedded_password" }}'
            postgresPassword: '{{repl ConfigOption "postgres_embedded_password" }}'
    - when: '{{repl ConfigOptionEquals "postgres_type" "external" }}'
      recursiveMerge: true
      values:
        postgresql:
          enabled: false
        externalDatabase:
          host: '{{repl ConfigOption "postgres_host" }}'
          port: repl{{ ConfigOption "postgres_port" }}
          database: '{{repl ConfigOption "postgres_database" }}'
          username: '{{repl ConfigOption "postgres_username" }}'
          password: '{{repl ConfigOption "postgres_password" }}'
    - when: '{{repl ConfigOptionEquals "plaid_enabled" "enabled" }}'
      recursiveMerge: true
      values:
        backend:
          plaid:
            enabled: true
            clientId: '{{repl ConfigOption "plaid_client_id" }}'
            secret: '{{repl ConfigOption "plaid_secret" }}'
    - when: '{{repl ConfigOptionEquals "teller_enabled" "enabled" }}'
      recursiveMerge: true
      values:
        backend:
          teller:
            enabled: true
            applicationId: '{{repl ConfigOption "teller_application_id" }}'
