apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: asset-tracker
spec:
  chart:
    name: asset-tracker
    chartVersion: 0.1.0
  releaseName: asset-tracker
  weight: 20
  values:
    ingress:
      enabled: true
      className: nginx
    ingress-nginx:
      enabled: true
      controller:
        service:
          type: '{{repl if eq Distribution "embedded-cluster" }}NodePort{{repl else }}LoadBalancer{{repl end }}'
          nodePorts:
            http: '{{repl if eq Distribution "embedded-cluster" }}30080{{repl else }}{{repl end }}'
    backend:
      analyticsEnabled: '{{repl LicenseFieldValue "analytics_enabled" }}'
    mailpit:
      enabled: true
  optionalValues:
    - when: '{{repl ConfigOptionEquals "postgres_type" "embedded" }}'
      recursiveMerge: true
      values:
        postgresql:
          enabled: true
    - when: '{{repl ConfigOptionEquals "postgres_type" "external" }}'
      recursiveMerge: true
      values:
        postgresql:
          enabled: false
        externalDatabase:
          host: '{{repl ConfigOption "postgres_host" }}'
          port: repl{{ ConfigOption "postgres_port" }}
          database: '{{repl ConfigOption "postgres_database" }}'
          username: '{{repl ConfigOption "postgres_username" }}'
          password: '{{repl ConfigOption "postgres_password" }}'
    - when: '{{repl ConfigOptionEquals "plaid_enabled" "enabled" }}'
      recursiveMerge: true
      values:
        backend:
          plaid:
            enabled: true
            clientId: '{{repl ConfigOption "plaid_client_id" }}'
            secret: '{{repl ConfigOption "plaid_secret" }}'
    - when: '{{repl ConfigOptionEquals "teller_enabled" "enabled" }}'
      recursiveMerge: true
      values:
        backend:
          teller:
            enabled: true
            applicationId: '{{repl ConfigOption "teller_application_id" }}'
